### ISSUE TITLE
What is the state of this

### ISSUE THREAD

**Issue by woakes070048** [digineo/zammad-asterisk#1]
Hello i notice that you haven't made a commit in a while and we are looking for an integration like this. What is the state of the connector?

**Comment by corny** [comment]
It works for us :)
All you need is to compile it and to try the example.

**Comment by corny** [comment]
I just made a few improvements in the code: 1f85cfa92c96dacbf6c4f74707a942ef71764c7d
Currently I am working on adding the name to incoming calls and routing a call to specific phones.
