### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by Mancy** [digineo/zammad-asterisk#2]
Hello,
    Would you please update the README with more details on the installation process.

as for the first step I have got this error
`src/github.com/digineo/zammad-asterisk/asterisk.go:46: event.Channel.Id undefined (type *ari.Channel has no field or method Id, but does have ID)`
does the go compiler expect that zammad and asterisk are on the same server ? if no, should i compile in the asterisk server ? if yes, what if zammad and asterisk are on different servers

Thank you

**Comment by dmke** [comment]
Hey, thanks for catching this.

The upstream API of [abourget/ari](https://github.com/abourget/ari) seems to have changed some time ago. I've updated our code to match those changes.

You should get going again by running

```sh
go get install -u github.com/digineo/zammad-asterisk
```

(note the `-u` flag). Please note, we're not using this integration anymore. If the Zammad API has changed in the last year, running the `zammad-asterisk` binary will likely produce errors.
