### ISSUE TITLE
Generic CTI Interface Zammad

### ISSUE THREAD

**Issue by mattronix** [digineo/zammad-asterisk#3]
Hello :)

Sorry for the silly question but does this work with the new CTI plugin from Zammad?

**Comment by dmke** [comment]
Hello Matthew,

this is basically a small deamon you install besides and integrate into your Asteriks server. It will then listen to a few Asterisk events and forward them to a Zammad API endpoint.

We're not using Zammad anymore, so I cannot say whether this still actually works or not (this depends entirely on the stability of Zammads API).

If Zammad provides a new or "native" integration with Asterisk, I highly recommend their solution.
